"""
DevOps Learning AI Tutor — powered by Google ADK
"""

import os
import asyncio
from pathlib import Path
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from google import genai
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import FunctionTool
import google.adk.tools as adk_tools

load_dotenv()

# ─── FastAPI app ────────────────────────────────────────────────────────────

app = FastAPI(
    title="DevOps Learning AI Tutor",
    description="Agentic AI tutor for Docker, Kubernetes, Helm, and DevOps",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "https://your-app.example.com"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── Content directory ───────────────────────────────────────────────────────

CONTENT_DIR = Path(__file__).parent.parent / "content"
LABS_DIR = Path(__file__).parent.parent / "labs"

# ─── Tool definitions (the agent's capabilities) ─────────────────────────────

def get_lesson_content(topic: str, lesson_slug: str) -> dict:
    """
    Retrieve the full content of a specific lesson.

    Args:
        topic: Topic area — one of: docker, kubernetes, helm, observability, gitops
        lesson_slug: Lesson filename without extension, e.g. '06-enterprise-networking'

    Returns:
        dict with 'content' (markdown text) and 'path' fields.
    """
    lesson_path = CONTENT_DIR / topic / f"{lesson_slug}.md"
    if not lesson_path.exists():
        # Try finding by partial match
        matches = list((CONTENT_DIR / topic).glob(f"*{lesson_slug}*")) if (CONTENT_DIR / topic).exists() else []
        if not matches:
            return {"error": f"Lesson not found: {topic}/{lesson_slug}", "available": list_lessons(topic)}
        lesson_path = matches[0]

    return {
        "path": str(lesson_path.relative_to(CONTENT_DIR)),
        "content": lesson_path.read_text(),
    }


def list_lessons(topic: str = None) -> dict:
    """
    List available lessons, optionally filtered by topic.

    Args:
        topic: Optional topic filter (docker, kubernetes, helm, observability, gitops)

    Returns:
        dict mapping topics to lists of lesson filenames.
    """
    result = {}
    if topic:
        topics = [topic]
    else:
        topics = [d.name for d in CONTENT_DIR.iterdir() if d.is_dir()]

    for t in topics:
        topic_dir = CONTENT_DIR / t
        if topic_dir.exists():
            result[t] = sorted([f.stem for f in topic_dir.glob("*.md")])

    return result


def get_lab_exercise(topic: str, lab_name: str) -> dict:
    """
    Retrieve a hands-on lab exercise with its instructions and YAML files.

    Args:
        topic: Topic area (docker, kubernetes, helm)
        lab_name: Lab directory name, e.g. '01-network-policies'

    Returns:
        dict with lab README content and any accompanying YAML/Dockerfile content.
    """
    lab_path = LABS_DIR / topic / lab_name
    if not lab_path.exists():
        available = [d.name for d in (LABS_DIR / topic).iterdir() if d.is_dir()] if (LABS_DIR / topic).exists() else []
        return {"error": f"Lab not found: {topic}/{lab_name}", "available": available}

    files = {}
    for f in sorted(lab_path.glob("**/*")):
        if f.is_file():
            rel = str(f.relative_to(lab_path))
            files[rel] = f.read_text()

    return {"lab": lab_name, "topic": topic, "files": files}


def generate_quiz(topic: str, difficulty: str = "intermediate", num_questions: int = 5) -> dict:
    """
    Generate a quiz for a given topic and difficulty.
    The quiz will be generated by the AI based on the lesson content.

    Args:
        topic: Topic to quiz on (docker, kubernetes, helm, networking, security)
        difficulty: 'beginner', 'intermediate', or 'advanced'
        num_questions: Number of questions (1-10)

    Returns:
        dict with quiz metadata (actual questions generated by the model).
    """
    return {
        "topic": topic,
        "difficulty": difficulty,
        "num_questions": min(max(num_questions, 1), 10),
        "instruction": f"Generate {num_questions} {difficulty}-level quiz questions about {topic} in Kubernetes/DevOps context. For each question provide: question text, 4 options (A-D), correct answer, and explanation.",
    }


def validate_yaml(yaml_content: str, resource_type: str = "auto") -> dict:
    """
    Validate a Kubernetes YAML manifest for common mistakes.

    Args:
        yaml_content: The YAML content to validate
        resource_type: Kubernetes resource type hint (Deployment, Service, etc.)

    Returns:
        dict with validation results and suggestions.
    """
    import yaml

    try:
        docs = list(yaml.safe_load_all(yaml_content))
    except yaml.YAMLError as e:
        return {"valid": False, "error": f"YAML parse error: {e}", "suggestions": ["Fix YAML syntax first"]}

    issues = []
    suggestions = []

    for doc in docs:
        if not doc:
            continue
        kind = doc.get("kind", "Unknown")
        metadata = doc.get("metadata", {})
        spec = doc.get("spec", {})

        # Common checks
        if not metadata.get("labels"):
            issues.append(f"{kind} '{metadata.get('name', '?')}' has no labels")
            suggestions.append("Add labels for identification: app, version, team")

        if kind == "Deployment":
            containers = spec.get("template", {}).get("spec", {}).get("containers", [])
            for c in containers:
                resources = c.get("resources", {})
                if not resources.get("limits"):
                    issues.append(f"Container '{c.get('name')}' has no resource limits")
                    suggestions.append("Set resources.limits.cpu and resources.limits.memory")
                if not resources.get("requests"):
                    issues.append(f"Container '{c.get('name')}' has no resource requests")

                sec_ctx = c.get("securityContext", {})
                if sec_ctx.get("privileged"):
                    issues.append(f"Container '{c.get('name')}' runs as privileged — SECURITY RISK")
                if not sec_ctx.get("readOnlyRootFilesystem"):
                    suggestions.append(f"Consider readOnlyRootFilesystem: true for '{c.get('name')}'")

        if kind == "Service":
            if spec.get("type") == "NodePort":
                suggestions.append("Consider using ClusterIP + Ingress instead of NodePort for production")

    return {
        "valid": len(issues) == 0,
        "resource_count": len([d for d in docs if d]),
        "issues": issues,
        "suggestions": suggestions,
        "summary": f"Found {len(issues)} issue(s) and {len(suggestions)} suggestion(s)",
    }


def get_learning_path(goal: str, current_level: str = "beginner") -> dict:
    """
    Generate a personalized learning path based on the user's goal and current level.

    Args:
        goal: What the user wants to achieve, e.g. 'deploy microservices', 'pass CKA', 'set up GitOps'
        current_level: 'beginner', 'intermediate', or 'advanced'

    Returns:
        dict with ordered list of lessons and estimated completion time.
    """
    paths = {
        "cka": {
            "title": "CKA Certification Path",
            "lessons": [
                "kubernetes/01-introduction", "kubernetes/02-pods", "kubernetes/03-deployments",
                "kubernetes/04-services", "kubernetes/05-configmaps-secrets",
                "kubernetes/06-enterprise-networking", "kubernetes/07-ingress-load-balancing",
                "kubernetes/09-rbac-security",
            ],
        },
        "microservices": {
            "title": "Microservices on Kubernetes",
            "lessons": [
                "docker/01-introduction", "docker/03-dockerfile",
                "kubernetes/02-pods", "kubernetes/03-deployments", "kubernetes/04-services",
                "kubernetes/07-ingress-load-balancing", "kubernetes/08-service-mesh",
                "helm/01-introduction", "helm/04-advanced-patterns",
                "observability/01-prometheus-grafana",
            ],
        },
        "gitops": {
            "title": "GitOps & Platform Engineering",
            "lessons": [
                "kubernetes/03-deployments", "helm/01-introduction", "helm/04-advanced-patterns",
                "gitops/01-argocd", "kubernetes/09-rbac-security",
                "observability/01-prometheus-grafana",
            ],
        },
    }

    # Find best matching path
    goal_lower = goal.lower()
    matched = None
    for key, path in paths.items():
        if key in goal_lower or any(word in goal_lower for word in key.split()):
            matched = path
            break

    if not matched:
        matched = {
            "title": f"Custom path for: {goal}",
            "lessons": list_lessons(),
        }

    return {
        "goal": goal,
        "level": current_level,
        "path": matched,
        "tip": "Start with the first lesson and follow the order. Each lesson builds on the previous.",
    }


# ─── Tool instances ───────────────────────────────────────────────────────────

lesson_tool = FunctionTool(get_lesson_content)
list_tool = FunctionTool(list_lessons)
lab_tool = FunctionTool(get_lab_exercise)
quiz_tool = FunctionTool(generate_quiz)
yaml_tool = FunctionTool(validate_yaml)
path_tool = FunctionTool(get_learning_path)

# ─── Agent definition ─────────────────────────────────────────────────────────

SYSTEM_INSTRUCTION = """
You are DevOps Sensei — an expert AI tutor specializing in Docker, Kubernetes, Helm,
service meshes, GitOps, and enterprise cloud-native infrastructure.

Your teaching style:
- Start with clear concepts, then show real production-grade examples
- Always explain the "why" before the "how"
- Use concrete analogies for complex topics
- Highlight common pitfalls and enterprise best practices
- Encourage hands-on practice with labs

Your capabilities:
1. **Teach lessons** — use get_lesson_content to retrieve and explain lesson material
2. **Guide learning** — use get_learning_path to suggest what to study based on goals
3. **Set quizzes** — use generate_quiz to test knowledge, then evaluate answers
4. **Assign labs** — use get_lab_exercise to give hands-on practice exercises
5. **Review YAML** — use validate_yaml to review and improve Kubernetes manifests
6. **Answer questions** — draw on your deep DevOps expertise

When a user:
- Asks to "learn about X" → retrieve the lesson and teach it interactively
- Asks "what should I learn" → use get_learning_path with their goal
- Says "quiz me" → generate a quiz and evaluate their answers
- Pastes YAML → validate it and explain improvements
- Asks for a lab → retrieve and walk through a hands-on exercise

Always be encouraging, precise, and production-focused. Reference real tools (kubectl,
helm, argocd) with actual commands. Never give outdated advice.
"""

tutor_agent = Agent(
    model="gemini-2.0-flash",
    name="DevOpsSensei",
    description="Expert DevOps AI tutor for Docker, Kubernetes, Helm, and cloud-native infrastructure",
    instruction=SYSTEM_INSTRUCTION,
    tools=[lesson_tool, list_tool, lab_tool, quiz_tool, yaml_tool, path_tool],
)

# ─── Session management ───────────────────────────────────────────────────────

session_service = InMemorySessionService()
APP_NAME = "devops-learning-tutor"

runner = Runner(
    agent=tutor_agent,
    app_name=APP_NAME,
    session_service=session_service,
)

# ─── API models ───────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str
    session_id: str
    user_id: str = "anonymous"

class ChatResponse(BaseModel):
    response: str
    session_id: str
    tool_calls: list[dict] = []

# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """Send a message to the DevOps AI tutor and get a response."""
    from google.genai import types

    # Ensure session exists
    try:
        await session_service.get_session(
            app_name=APP_NAME,
            user_id=request.user_id,
            session_id=request.session_id,
        )
    except Exception:
        await session_service.create_session(
            app_name=APP_NAME,
            user_id=request.user_id,
            session_id=request.session_id,
        )

    user_message = types.Content(
        role="user",
        parts=[types.Part(text=request.message)],
    )

    final_response = ""
    tool_calls_made = []

    async for event in runner.run_async(
        user_id=request.user_id,
        session_id=request.session_id,
        new_message=user_message,
    ):
        if event.is_final_response() and event.content:
            final_response = "".join(
                p.text for p in event.content.parts if hasattr(p, "text")
            )
        # Capture tool calls for transparency
        if hasattr(event, "tool_call") and event.tool_call:
            tool_calls_made.append({
                "tool": event.tool_call.name,
                "args": dict(event.tool_call.args),
            })

    return ChatResponse(
        response=final_response,
        session_id=request.session_id,
        tool_calls=tool_calls_made,
    )


@app.get("/chat/stream")
async def chat_stream(message: str, session_id: str, user_id: str = "anonymous"):
    """Stream the AI tutor response token by token (SSE)."""
    from google.genai import types

    async def generate():
        try:
            await session_service.get_session(
                app_name=APP_NAME, user_id=user_id, session_id=session_id
            )
        except Exception:
            await session_service.create_session(
                app_name=APP_NAME, user_id=user_id, session_id=session_id
            )

        user_message = types.Content(
            role="user", parts=[types.Part(text=message)]
        )

        async for event in runner.run_async(
            user_id=user_id, session_id=session_id, new_message=user_message
        ):
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if hasattr(part, "text") and part.text:
                        yield f"data: {part.text}\n\n"

        yield "data: [DONE]\n\n"

    return StreamingResponse(generate(), media_type="text/event-stream")


@app.get("/lessons")
async def list_all_lessons():
    """List all available lessons."""
    return list_lessons()


@app.get("/lessons/{topic}/{slug}")
async def get_lesson(topic: str, slug: str):
    """Retrieve a specific lesson's content."""
    result = get_lesson_content(topic, slug)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result


@app.get("/health")
async def health():
    return {"status": "ok", "agent": tutor_agent.name}


# ─── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
